---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

***Describe how you have improved as a practitioner and student of data science this quarter through your work in the course.***

-   Focus specifically on data science concepts and the skills we employed in learning them, not a laundry list of topics that you learned (those are in the syllabus, so I know them already).

-   Focus on a small number of specific areas of growth for you that happened in STAT 331. Identify at least one artifact in your portfolio that illustrates each area of growth and explain how this artifact shows growth in the way you are describing.

During my time in this class, I have had the opportunity to think more like a data scientist than an environmentalist. My growth as a data scientist can be highlighted by two keys areas, those being data manipulation and analysis, and development of code structure and efficiency.

I started off this course with little experience working with large datasets. My main tool to manipulate data and create visualizations to support my conclusions was excel but, my introduction to R gives me a new tool to use for my future classes and applications beyond school. The simplest aspect of being able to mutate and filter the dataset on mass proved to be an invaluable skill that I learned and have used in nearly every single assignment in this class. The mutate() function in areas of the portfolio, such as WD-4 express its usefulness in taking data and generating new variables that could be used in future operations to solve necessary questions about the data, especially questions regarding averages and means of specific observations. Similarly, being able to select the variables that I want to work with was also a major proponent of my code, illistrated in section WD-2 in the portfolio. These two together have and will continue to be a major contributor to my ability to work through vast amounts of data narrow my focus on the aspects that will solves any questions I ask.

Structure was also a major proponent in this course. There are many ways to create code, but making readable and efficient code is paramount. I have had previous experience with coding, but I had to re-learn how to make code that others could decipher without me having to explain it. Luckily, we had plenty of practice, and were given a general template as to make the code professional and readable. Examples in R-2 of the portfolio demonstrate the structuring of the code in a way that prevents cluttering and confusion. In addition to the structuring of the code, the inclusion of pipelines (\|\>) with the code greatly assisted in the readability of the code, along with efficiency, allowing code to lack inputs that would have been needed to be added without the pipelines, intern, cluttering the code. This could bleed into the use of functions, as these make the backbone of efficiency within R code. Having access to these and learning how to use them allow me the ability to extensively alter the data to my liking. PE-1 within the portfolio includes an example of such a function, across(), which is useful in applying a function such as mutate to a large variety of columns, saving processing power and improving readability.

These all come together in a way that have bolstered my ability to understand how to work data to solve my questions. I can now reach my conclusions in an effective manner and present the source code in a way that I could be proud of. Going through the portfolio, the complexity increases overtime, showing improves over the duration of the course and implementation of more advanced coding techniques to improve data interpretation and manipulation.
